services:
  wingtech-bot:
    image: wingtech-bot
    build:
      context: ./WingTechBot
      dockerfile: Dockerfile
    container_name: wingtech-bot
    restart: unless-stopped
    ports:
      - 5000:5000
      - 8080:80

    # These values come from .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}

  wingtech-bot-postgres:
    image: postgres:15
    container_name: wingtech-bot-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: wingtech-bot-frontend
    ports:
      - "80:80"

volumes:
  postgres_data:

