services:
  wingtech-bot:
    image: wingtech-bot
    build:
      context: ./WingTechBot
      dockerfile: Dockerfile

    container_name: wingtech-bot
    restart: unless-stopped
    tty: true # Essential for colored text output

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - ${WTB_PORT}:5000

    # These values come from .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}

  wingtech-bot-postgres:
    image: postgres:15
    container_name: wingtech-bot-postgres
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - ${DATABASE_HOST_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: wingtech-bot-frontend

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - "80:80"

volumes:
  postgres_data:

